name: DotNet Development

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@v1.1

      - name: Restore dependencies
        run: nuget restore src\Wpf.Ui.sln

      - name: Build the solution
        run: msbuild src\Wpf.Ui.Gallery.sln -p:Configuration=Release -m -graph -isolate

      - name: Publish .NET 7 WPF UI Gallery
        uses: actions/upload-artifact@v3
        id: publish_gallery
        with:
          name: WPF UI Gallery
          path: |
            src\Wpf.Ui.Gallery\bin\Release\net7.0-windows10.0.22621.0
