name: wpf-ui-cd-extension

on:
  push:
    branches: [main]
    paths:
      - 'src/Wpf.Ui.Extension**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Setup .NET Core SDK 10.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: Restore dependencies
        run: nuget restore Wpf.Ui.sln

      - name: Build the solution
        run: msbuild src\Wpf.Ui.Extension\Wpf.Ui.Extension.csproj /t:Rebuild -p:Configuration=Release -p:RestorePackages=false -p:Platform="x64"  -p:ProductArchitecture="amd64" -p:GITHUB_ACTIONS=True -p:LangVersion=8.0

      - name: Build the solution
        run: msbuild src\Wpf.Ui.Extension\Wpf.Ui.Extension.csproj /t:Rebuild -p:Configuration=Release -p:RestorePackages=false -p:Platform="arm64" -p:ProductArchitecture="arm64" -p:GITHUB_ACTIONS=True -p:LangVersion=8.0

      - uses: actions/upload-artifact@v4
        with:
          name: wpf-ui-vs22-extension-x64
          path: src\Wpf.Ui.Extension\bin\x64\Release\Wpf.Ui.Extension.vsix

      - uses: actions/upload-artifact@v4
        with:
          name: wpf-ui-vs22-extension-arm64
          path: src\Wpf.Ui.Extension\bin\arm64\Release\Wpf.Ui.Extension.vsix
